services:
  ha-lightdash:
    build:
      context: ./addons/lightdash
    container_name: ha-lightdash
    restart: unless-stopped
    ports:
      - "8001:8000"
    environment:
      HA_URL: "http://192.168.1.37:8123"
      HA_TOKEN: "${HA_TOKEN}"
    volumes:
      - lightdash_data:/data

volumes:
  lightdash_data:
