services:
  ha-lightdash:
    build:
      context: ./addons/lightdash
    container_name: ha-lightdash
    restart: unless-stopped
    ports:
      - "8001:8000"
    volumes:
      - lightdash_data:/data

volumes:
  lightdash_data:
